### ISSUE TITLE
Cannot copy paste via keyboard?

### ISSUE THREAD

**Issue by Bandgren** [PopAndCode/Superbus#10]
Is it expected that one cannot copy/paste via the keyboard?

**Comment by MonsieurTib** [comment]
related to #8 
Currently in development, meanwhile you can right click to paste

**Comment by MonsieurTib** [comment]
Hi @Bandgren ,
release is waiting for apple approval.

**Comment by MonsieurTib** [comment]
new release available. I close the issue
