### ISSUE TITLE
Cannot see message body due to text colour

### ISSUE THREAD

**Issue by leoncp** [PopAndCode/Superbus#6]
Hi, I'm needing to add new messages but I cannot see the Message Body because the text colour is black on the dark background.
Will subscribe if you can fix this, otherwise, I can't use it.
Many thanks,
Leon

**Comment by MonsieurTib** [comment]
Hi,
can you give more details please :
- is the text color black when you input directly in text box (no copy/paste from a formated source )?
- what theme/mode are you using, Dark or Light ?

**Comment by leoncp** [comment]
Hi,

- My Mac is in light mode... 
- Superbus is dark and the body section is almost black, when I type/input directly (or paste) in the "Body" section (New Message) then the text is black.

**Comment by MonsieurTib** [comment]
Ok, i will try in light mode (my mac is in Dark).

**Comment by MonsieurTib** [comment]
Bug is fixed and release approved by apple. I will publish next Monday.

**Comment by MonsieurTib** [comment]
Release published. I close this issue.

**Comment by leoncp** [comment]
Hi,

Thank you for the update... could I ask that you also update the text color
in queues?  Image attached... you will see that the no message found is
black on gray.

Many thanks,
Leon

[image: image.png]

**Comment by MonsieurTib** [comment]
There is no image attached

**Comment by leoncp** [comment]
Hi, have resent with the png.
Take care,
Leon

**Comment by MonsieurTib** [comment]
Hi, I'm sorry but i can see any image.

**Comment by leoncp** [comment]
Sent the image via email... attaching it here in Github.

![Snip20220713_19](https://user-images.githubusercontent.com/4377173/178711859-cc324c58-c20b-4c20-a99a-1acd5e78ef2b.png)

**Comment by MonsieurTib** [comment]
Ok I see image attached now. I'll fix that asap.
