### ISSUE TITLE
Superbus crashes after placing a message in a Queue

### ISSUE THREAD

**Issue by leoncp** [PopAndCode/Superbus#7]
Hi, I have an Azure function which dequeues messages from a Service Bus Queue.
When I use Superbus to place a message in the Queue it works the first time... and then it seems to do a hard crash when I send another message.

Other issues are that I cannot see the cursor when typing in messages.

**Comment by MonsieurTib** [comment]
Hi @leoncp ,
I'll fix this issue ASAP, probably this wk.

**Comment by MonsieurTib** [comment]
new release published.
